#!/bin/bash

main() {
    if [ -z $1 ]; then
        echo "Error: project name is empty"
        return
    fi

    local readonly index=$(cat ./projects.json | jq .index)
    local readonly new_project="$(printf "%04d_%s" $(($index + 1)) $1)"

    mkdir $new_project
    cd $new_project
    pio project init --board upesy_wroom --project-option="monitor_speed=115200"
    cd ..

    # update projects.json
    echo "$(cat ./projects.json | jq --arg index $(($index + 1)) '.index |= ($index|tonumber)')" > projects.json | jq
    # update iot-training.code-workspace
    local readonly workspace_json="$(cat ./iot-training.code-workspace | jq --arg project $new_project '.folders += [ {name: $project, path: $project} ]')"
    echo $workspace_json > ./iot-training.code-workspace | jq
}

main "${@}"
